# One-off: merge norm_lib_rules.json with new_rules.json and add review_type to CONS-001..025
import json

legacy_review = {
    "CONS-001": ("CONSISTENCY_VALUE_MISMATCH", "KEY_FIELD_INCONSISTENT"),
    "CONS-002": ("BUSINESS_LOGIC_PROHIBITION_VIOLATION", "BUSINESS_LOGIC_PROHIBITION_VIOLATION"),
    "CONS-003": ("CONSISTENCY_VALUE_MISMATCH", "CONSISTENCY_VALUE_MISMATCH"),
    "CONS-004": ("CONSISTENCY_TEXT_MISMATCH", "KEY_FIELD_INCONSISTENT"),
    "CONS-005": ("CONSISTENCY_TEXT_MISMATCH", "KEY_FIELD_INCONSISTENT"),
    "CONS-006": ("CONSISTENCY_TEXT_MISMATCH", "KEY_FIELD_INCONSISTENT"),
    "CONS-007": ("CONSISTENCY_TEXT_MISMATCH", "CONSISTENCY_TEXT_MISMATCH"),
    "CONS-008": ("CONSISTENCY_TEXT_MISMATCH", "CONSISTENCY_TEXT_MISMATCH"),
    "CONS-009": ("CONSISTENCY_TEXT_MISMATCH", "CONSISTENCY_TEXT_MISMATCH"),
    "CONS-010": ("CONSISTENCY_VALUE_MISMATCH", "CONSISTENCY_VALUE_MISMATCH"),
    "CONS-011": ("CONSISTENCY_VALUE_MISMATCH", "CONSISTENCY_VALUE_MISMATCH"),
    "CONS-012": ("CONSISTENCY_VALUE_MISMATCH", "CONSISTENCY_VALUE_MISMATCH"),
    "CONS-013": ("CONSISTENCY_VALUE_MISMATCH", "CONSISTENCY_VALUE_MISMATCH"),
    "CONS-014": ("CONSISTENCY_TEXT_MISMATCH", "CONSISTENCY_TEXT_MISMATCH"),
    "CONS-015": ("CONSISTENCY_TEXT_MISMATCH", "CONSISTENCY_TEXT_MISMATCH"),
    "CONS-016": ("CONSISTENCY_TEXT_MISMATCH", "CONSISTENCY_TEXT_MISMATCH"),
    "CONS-017": ("CONSISTENCY_VALUE_MISMATCH", "CONSISTENCY_VALUE_MISMATCH"),
    "CONS-018": ("CONSISTENCY_TEXT_MISMATCH", "CONSISTENCY_TEXT_MISMATCH"),
    "CONS-019": ("CONSISTENCY_TEXT_MISMATCH", "CONSISTENCY_TEXT_MISMATCH"),
    "CONS-020": ("CONSISTENCY_VALUE_MISMATCH", "CONSISTENCY_VALUE_MISMATCH"),
    "CONS-021": ("CONSISTENCY_TEXT_MISMATCH", "CONSISTENCY_TEXT_MISMATCH"),
    "CONS-022": ("CONSISTENCY_TEXT_MISMATCH", "CONSISTENCY_TEXT_MISMATCH"),
    "CONS-023": ("CONSISTENCY_TEXT_MISMATCH", "CONSISTENCY_TEXT_MISMATCH"),
    "CONS-024": ("CONSISTENCY_VALUE_MISMATCH", "CONSISTENCY_VALUE_MISMATCH"),
    "CONS-025": ("FORMAT", "FORMAT_REVIEW"),
}

with open("app/ai/norm_lib_rules.json", "r", encoding="utf-8") as f:
    old = json.load(f)
with open("new_rules.json", "r", encoding="utf-8") as f:
    new_rules = json.load(f)
for r in old:
    rid = r.get("rule_id")
    if rid in legacy_review:
        r["review_type"], r["category_code"] = legacy_review[rid]
merged = old + new_rules
with open("app/ai/norm_lib_rules.json", "w", encoding="utf-8") as f:
    json.dump(merged, f, ensure_ascii=False, indent=2)
print("Merged", len(old), "+", len(new_rules), "=", len(merged), "rules")
